dataset:
  class: cdc.CDCNaiveDataset
  data_root: data
  batch_size: 128

model:
  name: CDCNaiveNet
  class: cdc.cdc_net.CDCNaiveNet

  # configure the architecture here
  # all the entries are passed as arguments to cdc.cdc_net.CDCNaiveNet._create_model

  optimizer:
    class: AdamOptimizer
    learning_rate: 0.0001
  session_config: {gpu_options: {allow_growth: true}}

  inputs: [images, labels]
  outputs: [loss, accuracy]

main_loop:
  extra_streams: [valid]
  skip_zeroth_epoch: True

hooks:
  - ShowProgress
  - ComputeStats:
      variables: [loss, accuracy]
  - LogVariables
  - LogProfile
  - SaveEvery
  - SaveBest
  - CatchSigint
  - StopAfter:
      epochs: 300
  - cxflow_tensorflow.hooks.WriteTensorBoard
